// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace test {

static const char* TestService_method_names[] = {
  "/test.TestService/TestMessage",
};

std::unique_ptr< TestService::Stub> TestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestService::Stub> stub(new TestService::Stub(channel, options));
  return stub;
}

TestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TestMessage_(TestService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestService::Stub::TestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::test::TestReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::test::TestRequest, ::test::TestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TestMessage_, context, request, response);
}

void TestService::Stub::async::TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::test::TestRequest, ::test::TestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TestMessage_, context, request, response, std::move(f));
}

void TestService::Stub::async::TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TestMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test::TestReply>* TestService::Stub::PrepareAsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::test::TestReply, ::test::TestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TestMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::test::TestReply>* TestService::Stub::AsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTestMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

TestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestService::Service, ::test::TestRequest, ::test::TestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::test::TestRequest* req,
             ::test::TestReply* resp) {
               return service->TestMessage(ctx, req, resp);
             }, this)));
}

TestService::Service::~Service() {
}

::grpc::Status TestService::Service::TestMessage(::grpc::ServerContext* context, const ::test::TestRequest* request, ::test::TestReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

