// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace test {

// The test service definition.
class TestService final {
 public:
  static constexpr char const* service_full_name() {
    return "test.TestService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a test message
    virtual ::grpc::Status TestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::test::TestReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>> AsyncTestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>>(AsyncTestMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>> PrepareAsyncTestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>>(PrepareAsyncTestMessageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a test message
      virtual void TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>* AsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::test::TestReply>* PrepareAsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status TestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::test::TestReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::TestReply>> AsyncTestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::TestReply>>(AsyncTestMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::TestReply>> PrepareAsyncTestMessage(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::TestReply>>(PrepareAsyncTestMessageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, std::function<void(::grpc::Status)>) override;
      void TestMessage(::grpc::ClientContext* context, const ::test::TestRequest* request, ::test::TestReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::test::TestReply>* AsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::test::TestReply>* PrepareAsyncTestMessageRaw(::grpc::ClientContext* context, const ::test::TestRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TestMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a test message
    virtual ::grpc::Status TestMessage(::grpc::ServerContext* context, const ::test::TestRequest* request, ::test::TestReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TestMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTestMessage(::grpc::ServerContext* context, ::test::TestRequest* request, ::grpc::ServerAsyncResponseWriter< ::test::TestReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TestMessage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TestMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::test::TestRequest, ::test::TestReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::test::TestRequest* request, ::test::TestReply* response) { return this->TestMessage(context, request, response); }));}
    void SetMessageAllocatorFor_TestMessage(
        ::grpc::MessageAllocator< ::test::TestRequest, ::test::TestReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::test::TestRequest, ::test::TestReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TestMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_TestMessage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TestMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TestMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTestMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TestMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TestMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TestMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TestMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TestMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::test::TestRequest, ::test::TestReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::test::TestRequest, ::test::TestReply>* streamer) {
                       return this->StreamedTestMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TestMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TestMessage(::grpc::ServerContext* /*context*/, const ::test::TestRequest* /*request*/, ::test::TestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTestMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::test::TestRequest,::test::TestReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TestMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TestMessage<Service > StreamedService;
};

}  // namespace test


#endif  // GRPC_test_2eproto__INCLUDED
